# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: race-records

  rails:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - ./:/srv
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
        - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
