AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:
    SaveRecord:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                SaveRecord:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /record
                        Method: post
    SaveReading:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                SaveReading:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /reading
                        Method: post
Outputs:

    SaveRecordApi:
      Description: "API Gateway endpoint URL for Prod stage for Save Record function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/record/"

    SaveRecordFunction:
      Description: "Save Record Lambda Function ARN"
      Value: !GetAtt SaveRecordFunction.Arn

    SaveRecordFunctionIamRole:
      Description: "Implicit IAM Role created for Save Record function"
      Value: !GetAtt SaveRecordFunctionRole.Arn

    SaveReadingApi:
      Description: "API Gateway endpoint URL for Prod stage for Save Reading function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/reading/"

    SaveReadingFunction:
      Description: "Save Reading Lambda Function ARN"
      Value: !GetAtt SaveReadingFunction.Arn

    SaveReadingFunctionIamRole:
      Description: "Implicit IAM Role created for Save Reading function"
      Value: !GetAtt SaveReadingFunctionRole.Arn
